#!/bin/sh
# Generated by dot2net. The entry point for this lab on containerlab: run it
# from anywhere, it works out where its files are.
#
# destroy does more than containerlab's own: it runs the lab's teardown
# commands, copies out what the lab was asked to bring back, and only then
# takes the lab down. A step that fails is named and the rest still runs - a
# lab left standing because something could not be copied is worse than the
# missing file - and the script ends non-zero so that whatever called it knows.
cd "$(dirname "$0")"
TOPO="topo.yaml"
COLLECT_DIR="${DOT2NET_COLLECT_DIR:-collected}"
# Who the collected files should belong to: the user who ran this, whether or
# not they went through sudo.
OWNER="${SUDO_USER:-$(id -un)}"

# Root without stacking sudo. A sudo inside a sudo'ed script replaces SUDO_USER
# with root, and Kathara puts a lab in the namespace of the user it thinks asked
# for it - so a lab started by hand would be invisible here, and destroy would
# report success having removed nothing. The other platforms do not care, but
# they run the same way so that all three are read the same.
SUDO=sudo
[ "$(id -u)" -eq 0 ] && SUDO=""

failed=""
note_failure() {
  failed="$failed
  $1"
  echo "dot2net: FAILED $1" >&2
}
report() {
  [ -n "$failed" ] || return 0
  echo "dot2net: these steps failed:$failed" >&2
  exit 1
}

# containerlab labels a container with the lab it belongs to and the node it is,
# and both are needed: another lab on this machine may well have a node of the
# same name, and teardown and collect must not reach into it.
container_id() {
  $SUDO docker ps -q \
    --filter "label=containerlab=ospf" \
    --filter "label=clab-node-name=$1" | head -1
}

# Commands the lab wants run inside a node while it is still up. The block is
# fed to a shell on stdin so that it can be more than one line.
teardown_node() {
  node="$1"
  cid=$(container_id "$node")
  if [ -z "$cid" ]; then
    note_failure "teardown $node: no container"
    cat >/dev/null
    return
  fi
  $SUDO docker exec -i "$cid" sh -s || note_failure "teardown $node"
}

collect_file() {
  node="$1"
  path="$2"
  cid=$(container_id "$node")
  if [ -z "$cid" ]; then
    note_failure "collect $node:$path: no container"
    return
  fi
  dest="$COLLECT_DIR/$node$path"
  mkdir -p "$(dirname "$dest")"
  $SUDO docker cp "$cid:$path" "$dest" || note_failure "collect $node:$path"
  # docker cp keeps the ownership the file had in the container, and this
  # script runs under sudo, so both what came back and the directories holding
  # it belong to root - unreadable and undeletable by the person who asked for
  # them. Hand the whole lot over.
  $SUDO chown -R "$OWNER" "$COLLECT_DIR" 2>/dev/null || true
}

run_teardown() {
  :

}

run_collect() {
  :
  collect_file r1 /var/log/frr.log
  collect_file r2 /var/log/frr.log
  collect_file r3 /var/log/frr.log
  collect_file r4 /var/log/frr.log
}

# What the lab asked to have run on this machine, two functions per command
# this script takes: what goes before the command it gives containerlab, and
# what goes after. A block says which by its priority, and the blocks reach here
# already in order - see the wiki on machine-side hooks. Functions rather than
# the commands themselves, so that a block of several lines lands where a single
# line was written and note_failure works on it like anything else here.
run_worker_deploy_pre() {
  :

}

run_worker_deploy_post() {
  :

}

run_worker_exec_pre() {
  :

}

run_worker_exec_post() {
  :

}

run_worker_collect_pre() {
  :

}

run_worker_collect_post() {
  :

}

run_worker_destroy_pre() {
  :

}

run_worker_destroy_post() {
  :

}

case "${1:-deploy}" in
  deploy)
    # What the lab needs of the machine before containerlab is asked for
    # anything: the bridges a topology names have to exist before it will
    # deploy, since its check runs before any stage and nothing inside the lab
    # can make them.
    run_worker_deploy_pre
    report
    # Anything after "deploy" goes to containerlab: a caller running labs in
    # parallel has to place each one's management network itself
    # (--network, --ipv4-subnet), and there is nothing in a topology to say it
    # with. Dropping the arguments in silence would let the labs come up on one
    # subnet and collide later.
    [ $# -gt 0 ] && shift
    $SUDO containerlab deploy -t "$TOPO" "$@" || note_failure "deploy"
    # Anything that could not exist until now: the veth reaching a bridge is
    # made by containerlab as it brings the lab up, so a capture or a qdisc on
    # one is written here rather than above.
    run_worker_deploy_post
    report
    ;;
  destroy)
    run_teardown
    run_collect
    run_worker_destroy_pre
    $SUDO containerlab destroy -t "$TOPO" --cleanup || note_failure "destroy"
    run_worker_destroy_post
    report
    ;;
  collect)
    [ -n "$2" ] && COLLECT_DIR="$2"
    run_worker_collect_pre
    run_collect
    run_worker_collect_post
    report
    ;;
  exec)
    shift
    [ $# -ge 2 ] || { echo "usage: $0 exec <node> <command>..." >&2; exit 2; }
    node="$1"; shift
    # docker rather than `containerlab exec`, which takes the command as one
    # string: the words a caller quoted are already separate arguments here, and
    # joining them loses the quoting - `vtysh -c "show ip ospf neighbor"` would
    # reach vtysh as four words. TiNET and Kathara reach a container the same
    # way, for the same reason.
    cid=$(container_id "$node")
    [ -n "$cid" ] || { echo "$0: no container for node $node - is the lab up?" >&2; exit 1; }
    run_worker_exec_pre
    report
    $SUDO docker exec "$cid" "$@" || note_failure "exec $node"
    run_worker_exec_post
    report
    ;;
  *)
    echo "usage: $0 {deploy|destroy|collect [<dir>]|exec <node> <command>...}" >&2
    echo "  DOT2NET_COLLECT_DIR where collected files go" >&2
    exit 2
    ;;
esac
