#!/bin/sh
# Generated by dot2net. The entry point for this lab on containerlab: run it
# from anywhere, it works out where its files are.
#
# destroy does more than containerlab's own: it runs the lab's teardown
# commands, copies out what the lab was asked to bring back, and only then
# takes the lab down. A step that fails is named and the rest still runs - a
# lab left standing because something could not be copied is worse than the
# missing file - and the script ends non-zero so that whatever called it knows.
cd "$(dirname "$0")"
TOPO="topo.yaml"
COLLECT_DIR="${DOT2NET_COLLECT_DIR:-collected}"
# Who the collected files should belong to: the user who ran this, whether or
# not they went through sudo.
OWNER="${SUDO_USER:-$(id -un)}"

# Root without stacking sudo. A sudo inside a sudo'ed script replaces SUDO_USER
# with root, and Kathara puts a lab in the namespace of the user it thinks asked
# for it - so a lab started by hand would be invisible here, and destroy would
# report success having removed nothing. The other platforms do not care, but
# they run the same way so that all three are read the same.
SUDO=sudo
[ "$(id -u)" -eq 0 ] && SUDO=""

failed=""
note_failure() {
  failed="$failed
  $1"
  echo "dot2net: FAILED $1" >&2
}
report() {
  [ -n "$failed" ] || return 0
  echo "dot2net: these steps failed:$failed" >&2
  exit 1
}

# containerlab labels a container with the lab it belongs to and the node it is,
# and both are needed: another lab on this machine may well have a node of the
# same name, and teardown and collect must not reach into it.
container_id() {
  $SUDO docker ps -q \
    --filter "label=containerlab=bgp_evpn_vxlan_topo1" \
    --filter "label=clab-node-name=$1" | head -1
}

# Commands the lab wants run inside a node while it is still up. The block is
# fed to a shell on stdin so that it can be more than one line.
teardown_node() {
  node="$1"
  cid=$(container_id "$node")
  if [ -z "$cid" ]; then
    note_failure "teardown $node: no container"
    cat >/dev/null
    return
  fi
  $SUDO docker exec -i "$cid" sh -s || note_failure "teardown $node"
}

collect_file() {
  node="$1"
  path="$2"
  cid=$(container_id "$node")
  if [ -z "$cid" ]; then
    note_failure "collect $node:$path: no container"
    return
  fi
  dest="$COLLECT_DIR/$node$path"
  mkdir -p "$(dirname "$dest")"
  $SUDO docker cp "$cid:$path" "$dest" || note_failure "collect $node:$path"
  # docker cp keeps the ownership the file had in the container, and this
  # script runs under sudo, so both what came back and the directories holding
  # it belong to root - unreadable and undeletable by the person who asked for
  # them. Hand the whole lot over.
  $SUDO chown -R "$OWNER" "$COLLECT_DIR" 2>/dev/null || true
}

run_teardown() {
  :

}

run_collect() {
  :
  collect_file host1 /var/log/frr.log
  collect_file host2 /var/log/frr.log
  collect_file p1 /var/log/frr.log
  collect_file pe1 /var/log/frr.log
  collect_file pe2 /var/log/frr.log
  collect_file pe3 /var/log/frr.log
}

case "${1:-deploy}" in
  deploy)
    # The bridges a topology names have to exist before containerlab will
    # deploy: its check runs before any stage, so nothing inside the lab can
    # make them. setup-bridges.sh is written beside this script when the
    # topology asks for a bridge, and destroy takes the same ones down again.
    if [ -f ./setup-bridges.sh ]; then
      $SUDO ./setup-bridges.sh || { note_failure "setup-bridges"; exit 1; }
    fi
    # Anything after "deploy" goes to containerlab: a caller running labs in
    # parallel has to place each one's management network itself
    # (--network, --ipv4-subnet), and there is nothing in a topology to say it
    # with. Dropping the arguments in silence would let the labs come up on one
    # subnet and collide later.
    [ $# -gt 0 ] && shift
    exec $SUDO containerlab deploy -t "$TOPO" "$@"
    ;;
  destroy)
    run_teardown
    run_collect
    $SUDO containerlab destroy -t "$TOPO" --cleanup || note_failure "destroy"

    report
    ;;
  collect)
    [ -n "$2" ] && COLLECT_DIR="$2"
    run_collect
    report
    ;;
  exec)
    shift
    [ $# -ge 2 ] || { echo "usage: $0 exec <node> <command>..." >&2; exit 2; }
    node="$1"; shift
    # docker rather than `containerlab exec`, which takes the command as one
    # string: the words a caller quoted are already separate arguments here, and
    # joining them loses the quoting - `vtysh -c "show ip ospf neighbor"` would
    # reach vtysh as four words. TiNET and Kathara reach a container the same
    # way, for the same reason.
    cid=$(container_id "$node")
    [ -n "$cid" ] || { echo "$0: no container for node $node - is the lab up?" >&2; exit 1; }
    exec $SUDO docker exec "$cid" "$@"
    ;;
  *)
    echo "usage: $0 {deploy|destroy|collect [<dir>]|exec <node> <command>...}" >&2
    echo "  DOT2NET_COLLECT_DIR where collected files go" >&2
    exit 2
    ;;
esac
