#!/bin/sh
# Generated by dot2net. The entry point for this lab on containerlab: run it
# from anywhere, it works out where its files are.
#
# destroy does more than containerlab's own: it runs the lab's teardown
# commands, copies out what the lab was asked to bring back, and only then
# takes the lab down. A step that fails is named and the rest still runs - a
# lab left standing because something could not be copied is worse than the
# missing file - and the script ends non-zero so that whatever called it knows.
cd "$(dirname "$0")"
TOPO="topo.yaml"
COLLECT_DIR="${DOT2NET_COLLECT_DIR:-collected}"
# Who the collected files should belong to: the user who ran this, whether or
# not they went through sudo.
OWNER="${SUDO_USER:-$(id -un)}"

# Root without stacking sudo. A sudo inside a sudo'ed script replaces SUDO_USER
# with root, and Kathara puts a lab in the namespace of the user it thinks asked
# for it - so a lab started by hand would be invisible here, and destroy would
# report success having removed nothing. The other platforms do not care, but
# they run the same way so that all three are read the same.
SUDO=sudo
[ "$(id -u)" -eq 0 ] && SUDO=""

failed=""
note_failure() {
  failed="$failed
  $1"
  echo "dot2net: FAILED $1" >&2
}
report() {
  [ -n "$failed" ] || return 0
  echo "dot2net: these steps failed:$failed" >&2
  exit 1
}

# containerlab labels a container with the lab it belongs to and the node it is,
# and both are needed: another lab on this machine may well have a node of the
# same name, and teardown and collect must not reach into it.
container_id() {
  $SUDO docker ps -q \
    --filter "label=containerlab=ospf" \
    --filter "label=clab-node-name=$1" | head -1
}

# Commands the lab wants run inside a node while it is still up. The block is
# fed to a shell on stdin so that it can be more than one line.
teardown_node() {
  node="$1"
  cid=$(container_id "$node")
  if [ -z "$cid" ]; then
    note_failure "teardown $node: no container"
    cat >/dev/null
    return
  fi
  $SUDO docker exec -i "$cid" sh -s || note_failure "teardown $node"
}

collect_file() {
  node="$1"
  path="$2"
  cid=$(container_id "$node")
  if [ -z "$cid" ]; then
    note_failure "collect $node:$path: no container"
    return
  fi
  dest="$COLLECT_DIR/$node$path"
  mkdir -p "$(dirname "$dest")"
  $SUDO docker cp "$cid:$path" "$dest" || note_failure "collect $node:$path"
  # docker cp keeps the ownership the file had in the container, and this
  # script runs under sudo, so both what came back and the directories holding
  # it belong to root - unreadable and undeletable by the person who asked for
  # them. Hand the whole lot over.
  $SUDO chown -R "$OWNER" "$COLLECT_DIR" 2>/dev/null || true
}

run_teardown() {
  :

}

run_collect() {
  :
  collect_file r1 /var/log/frr.log
  collect_file r2 /var/log/frr.log
  collect_file r3 /var/log/frr.log
  collect_file r4 /var/log/frr.log
}

# What the lab asked to have run on this machine, one function per command this
# script takes. containerlab's own command is one of the blocks in each list,
# not something the list is wrapped around, so a block says whether it runs
# before or after it the same way it says anything else about its place - see
# the wiki on machine-side hooks. The blocks reach here already in order.
#
# Functions rather than the commands themselves, so that a block of several
# lines lands where a single line was written and note_failure works on it like
# anything else here.
run_worker_deploy() {
  :
  # Nothing is given to containerlab if the machine could not be made ready: a
  # bridge that was not created is a lab that comes up wrong rather than one that
  # fails, and this is where that is still cheap to say.
  report
  $SUDO containerlab deploy -t "$TOPO" "$@" || note_failure "deploy"
}

run_worker_exec() {
  :
  report
  $SUDO docker exec "$cid" "$@"
  status=$?
}

run_worker_collect() {
  :
  run_collect
}

run_worker_destroy() {
  :
  $SUDO containerlab destroy -t "$TOPO" --cleanup || note_failure "destroy"
}

case "${1:-deploy}" in
  deploy)
    # Everything the lab needs of the machine, and containerlab's own deploy
    # among it: the bridges a topology names have to exist before containerlab
    # will deploy, and a capture on a veth cannot be taken until it has, so the
    # commands sit either side of the deploy in one list.
    #
    # Anything after "deploy" goes to containerlab: a caller running labs in
    # parallel has to place each one's management network itself (--network,
    # --ipv4-subnet), and there is nothing in a topology to say it with.
    # Dropping the arguments in silence would let the labs come up on one subnet
    # and collide later.
    [ $# -gt 0 ] && shift
    run_worker_deploy "$@"
    report
    ;;
  destroy)
    run_teardown
    run_collect
    run_worker_destroy
    report
    ;;
  collect)
    [ -n "$2" ] && COLLECT_DIR="$2"
    run_worker_collect
    report
    ;;
  exec)
    shift
    [ $# -ge 2 ] || { echo "usage: $0 exec <node> <command>..." >&2; exit 2; }
    node="$1"; shift
    # docker rather than `containerlab exec`, which takes the command as one
    # string: the words a caller quoted are already separate arguments here, and
    # joining them loses the quoting - `vtysh -c "show ip ospf neighbor"` would
    # reach vtysh as four words. TiNET and Kathara reach a container the same
    # way, for the same reason.
    cid=$(container_id "$node")
    [ -n "$cid" ] || { echo "$0: no container for node $node - is the lab up?" >&2; exit 1; }
    # The command's own exit status is what a caller wants back - a test harness
    # runs something in a node and reads the code - so the block that runs it
    # keeps the status in $status, and it is given back here rather than
    # flattened into the script's own success or failure.
    status=0
    run_worker_exec "$@"
    report
    exit $status
    ;;
  *)
    echo "usage: $0 {deploy|destroy|collect [<dir>]|exec <node> <command>...}" >&2
    echo "  DOT2NET_COLLECT_DIR where collected files go" >&2
    exit 2
    ;;
esac
