LAB_NAME="host1"
r1[image]="quay.io/frrouting/frr:8.5.4"
r1[volume]="../r1/etc/frr|/etc/frr"
r1[0]="conn3"
r2[image]="quay.io/frrouting/frr:8.5.4"
r2[volume]="../r2/etc/frr|/etc/frr"
r2[0]="br1"
r2[1]="conn3"
