LAB_NAME="ospf_simple"
r1[image]="quay.io/frrouting/frr:8.5.4"
r1[volume]="../r1/etc/frr|/etc/frr"
r1[0]="conn0"
r2[image]="quay.io/frrouting/frr:8.5.4"
r2[volume]="../r2/etc/frr|/etc/frr"
r2[0]="conn0"
r2[1]="conn1"
r3[image]="quay.io/frrouting/frr:8.5.4"
r3[volume]="../r3/etc/frr|/etc/frr"
r3[0]="conn1"
