LAB_NAME="host2"
r3[image]="quay.io/frrouting/frr:8.5.4"
r3[volume]="../r3/etc/frr|/etc/frr"
r3[0]="sw1_host2"
r4[image]="quay.io/frrouting/frr:8.5.4"
r4[volume]="../r4/etc/frr|/etc/frr"
r4[0]="sw1_host2"
