#!/bin/sh
# Generated by dot2net. The entry point for this lab on Kathara: run it from
# anywhere, it works out where its files are.
#
# Kathara reads lab.conf and <device>.startup from the directory it runs in, so
# this script changes into it first. Everything that reaches into a device goes
# through docker: kathara exec cannot pass a command containing -c.
#
# destroy does more than Kathara's own: it runs the lab's teardown commands,
# copies out what the lab was asked to bring back, and only then takes the lab
# down. A step that fails is named and the rest still runs, and the script ends
# non-zero so that whatever called it knows.
cd "$(dirname "$0")"
COLLECT_DIR="${DOT2NET_COLLECT_DIR:-../collected}"
# Who the collected files should belong to: the user who ran this, whether or
# not they went through sudo.
OWNER="${SUDO_USER:-$(id -un)}"

# Root without stacking sudo. A sudo inside a sudo'ed script replaces SUDO_USER
# with root, and Kathara puts a lab in the namespace of the user it thinks asked
# for it - so a lab started by hand would be invisible here, and destroy would
# report success having removed nothing. The other platforms do not care, but
# they run the same way so that all three are read the same.
SUDO=sudo
[ "$(id -u)" -eq 0 ] && SUDO=""

failed=""
note_failure() {
  failed="$failed
  $1"
  echo "dot2net: FAILED $1" >&2
}
report() {
  [ -n "$failed" ] || return 0
  echo "dot2net: these steps failed:$failed" >&2
  exit 1
}

# Kathara labels a container with the device it is, which is an exact match where
# the container's own name - user, lab and device run together - is not. A lab
# generated under a name of its own carries that name in front of every device,
# so two labs from one topology can be up at once without this reaching into the
# wrong one. A caller still names the node as the topology does.
container_id() { $SUDO docker ps -q --filter "label=name=$1" | head -1; }

teardown_node() {
  node="$1"
  cid=$(container_id "$node")
  if [ -z "$cid" ]; then
    note_failure "teardown $node: no container"
    cat >/dev/null
    return
  fi
  $SUDO docker exec -i "$cid" sh -s || note_failure "teardown $node"
}

collect_file() {
  node="$1"
  path="$2"
  cid=$(container_id "$node")
  if [ -z "$cid" ]; then
    note_failure "collect $node:$path: no container"
    return
  fi
  dest="$COLLECT_DIR/$node$path"
  mkdir -p "$(dirname "$dest")"
  $SUDO docker cp "$cid:$path" "$dest" || note_failure "collect $node:$path"
  # docker cp keeps the ownership the file had in the container, and this
  # script runs under sudo, so both what came back and the directories holding
  # it belong to root - unreadable and undeletable by the person who asked for
  # them. Hand the whole lot over.
  $SUDO chown -R "$OWNER" "$COLLECT_DIR" 2>/dev/null || true
}

run_teardown() {
  :

}

run_collect() {
  :
  collect_file host1 /var/log/frr.log
  collect_file host2 /var/log/frr.log
  collect_file p1 /var/log/frr.log
  collect_file pe1 /var/log/frr.log
  collect_file pe2 /var/log/frr.log
  collect_file pe3 /var/log/frr.log
}

# What the lab asked to have run on this machine, one function per command this
# script takes. Each is a function rather than the commands themselves so that a
# block of several lines lands where a single line was written, and so that
# note_failure and report work on it like anything else here.
run_worker_deploy_pre() {
  :

}

run_worker_deploy_post() {
  :

}

run_worker_exec_pre() {
  :

}

run_worker_exec_post() {
  :

}

run_worker_collect_pre() {
  :

}

run_worker_collect_post() {
  :

}

run_worker_destroy_pre() {
  :

}

run_worker_destroy_post() {
  :

}

case "${1:-deploy}" in
  deploy)
    run_worker_deploy_pre
    report
    # Anything after "deploy" goes to kathara, the way it does for the other
    # platforms' scripts.
    [ $# -gt 0 ] && shift
    $SUDO kathara lstart --noterminals "$@" || note_failure "deploy"
    run_worker_deploy_post
    report
    ;;
  destroy)
    run_teardown
    run_collect
    run_worker_destroy_pre
    $SUDO kathara lclean || note_failure "destroy"
    run_worker_destroy_post
    report
    ;;
  collect)
    [ -n "$2" ] && COLLECT_DIR="$2"
    run_worker_collect_pre
    run_collect
    run_worker_collect_post
    report
    ;;
  exec)
    shift
    [ $# -ge 2 ] || { echo "usage: $0 exec <node> <command>..." >&2; exit 2; }
    node="$1"; shift
    cid=$(container_id "$node")
    [ -n "$cid" ] || { echo "$0: no container for node $node - is the lab up?" >&2; exit 1; }
    run_worker_exec_pre
    report
    $SUDO docker exec "$cid" "$@" || note_failure "exec $node"
    run_worker_exec_post
    report
    ;;
  *)
    echo "usage: $0 {deploy|destroy|collect [<dir>]|exec <node> <command>...}" >&2
    echo "  DOT2NET_COLLECT_DIR where collected files go" >&2
    exit 2
    ;;
esac
