LAB_NAME="bgp_evpn_vxlan_topo1"
host1[image]="quay.io/frrouting/frr:8.5.0"
host1[volume]="../host1/etc/frr|/etc/frr"
host1[0]="conn0"
host2[image]="quay.io/frrouting/frr:8.5.0"
host2[volume]="../host2/etc/frr|/etc/frr"
host2[0]="conn1"
p1[image]="quay.io/frrouting/frr:8.5.0"
p1[volume]="../p1/etc/frr|/etc/frr"
p1[0]="conn2"
p1[1]="conn3"
pe1[image]="quay.io/frrouting/frr:8.5.0"
pe1[volume]="../pe1/etc/frr|/etc/frr"
pe1[0]="conn5"
pe1[1]="conn6"
pe2[image]="quay.io/frrouting/frr:8.5.0"
pe2[volume]="../pe2/etc/frr|/etc/frr"
pe2[0]="conn7"
pe2[1]="conn8"
pe3[image]="quay.io/frrouting/frr:8.5.0"
pe3[volume]="../pe3/etc/frr|/etc/frr"
pe3[0]="conn9"
s1[image]="nicolaka/netshoot"
s1[0]="conn0"
s1[1]="conn5"
s2[image]="nicolaka/netshoot"
s2[0]="conn2"
s2[1]="conn6"
s2[2]="conn9"
s3[image]="nicolaka/netshoot"
s3[0]="conn3"
s3[1]="conn7"
s4[image]="nicolaka/netshoot"
s4[0]="conn1"
s4[1]="conn8"
