LAB_NAME="ospf-topo1"
r1[image]="nicolaka/netshoot"
r1[volume]="../r1/etc/frr|/etc/frr"
r1[0]="conn0"
r1[1]="conn1"
r2[image]="nicolaka/netshoot"
r2[volume]="../r2/etc/frr|/etc/frr"
r2[0]="conn2"
r2[1]="conn3"
r3[image]="nicolaka/netshoot"
r3[volume]="../r3/etc/frr|/etc/frr"
r3[0]="conn4"
r3[1]="conn5"
r3[2]="conn6"
r4[image]="nicolaka/netshoot"
r4[volume]="../r4/etc/frr|/etc/frr"
r4[0]="conn7"
r4[1]="conn8"
s1[image]="nicolaka/netshoot"
s1[0]="conn0"
s2[image]="nicolaka/netshoot"
s2[0]="conn2"
s3[image]="nicolaka/netshoot"
s3[0]="conn1"
s3[1]="conn3"
s3[2]="conn4"
s4[image]="nicolaka/netshoot"
s4[0]="conn5"
s5[image]="nicolaka/netshoot"
s5[0]="conn6"
s5[1]="conn7"
s6[image]="nicolaka/netshoot"
s6[0]="conn8"
