LAB_NAME="address_reservation"
leaf1[image]="slankdev/frr"
leaf1[0]="conn0"
leaf1[1]="conn1"
leaf1[2]="conn2"
leaf1[3]="conn3"
leaf2[image]="slankdev/frr"
leaf2[0]="conn4"
leaf2[1]="conn5"
leaf2[2]="conn6"
leaf2[3]="conn7"
leaf3[image]="slankdev/frr"
leaf3[0]="conn8"
leaf3[1]="conn9"
leaf3[2]="conn10"
leaf3[3]="conn11"
leaf4[image]="slankdev/frr"
leaf4[0]="conn12"
leaf4[1]="conn13"
leaf4[2]="conn14"
leaf4[3]="conn15"
spine1[image]="slankdev/frr"
spine1[0]="conn0"
spine1[1]="conn4"
spine1[2]="conn8"
spine1[3]="conn12"
spine2[image]="slankdev/frr"
spine2[0]="conn1"
spine2[1]="conn5"
spine2[2]="conn9"
spine2[3]="conn13"
sv1[image]="slankdev/frr"
sv1[0]="conn2"
sv2[image]="slankdev/frr"
sv2[0]="conn3"
sv3[image]="slankdev/frr"
sv3[0]="conn6"
sv4[image]="slankdev/frr"
sv4[0]="conn7"
sv5[image]="slankdev/frr"
sv5[0]="conn10"
sv6[image]="slankdev/frr"
sv6[0]="conn11"
sv7[image]="slankdev/frr"
sv7[0]="conn14"
sv8[image]="slankdev/frr"
sv8[0]="conn15"
