LAB_NAME="deploy_and_virtual"
r1[image]="nicolaka/netshoot"
r1[volume]="../r1/etc/net|/etc/net"
r1[0]="conn2"
r1[1]="sw"
r2[image]="nicolaka/netshoot"
r2[volume]="../r2/etc/net|/etc/net"
r2[0]="sw"
stock[image]="nicolaka/netshoot"
stock[0]="conn2"
