LAB_NAME="deploy_and_virtual"
edge1[image]="nicolaka/netshoot"
edge1[volume]="../edge1/etc/net|/etc/net"
edge1[0]="lan"
edge1[1]="conn2"
edge2[image]="nicolaka/netshoot"
edge2[volume]="../edge2/etc/net|/etc/net"
edge2[0]="lan"
probe[image]="nicolaka/netshoot"
probe[0]="conn2"
