ip forwarding
ipv6 forwarding
!
interface eth0
 ip address 10.0.0.1/24
!
interface eth1
 description to sw2 - RIPv2 interface
 ip address 10.0.1.1/24
 no link-detect
!
interface eth2
 ip address 10.0.2.1/24
!
interface eth3
 ip address 10.0.3.1/24
!
line vty
!