LAB_NAME="rip-topo1"
r1[image]="nicolaka/netshoot"
r1[volume]="../r1/etc/frr|/etc/frr"
r1[0]="conn0"
r1[1]="conn1"
r1[2]="conn2"
r1[3]="conn3"
r2[image]="nicolaka/netshoot"
r2[volume]="../r2/etc/frr|/etc/frr"
r2[0]="conn4"
r2[1]="conn5"
r3[image]="nicolaka/netshoot"
r3[volume]="../r3/etc/frr|/etc/frr"
r3[0]="conn6"
r3[1]="conn7"
sw1[image]="nicolaka/netshoot"
sw1[0]="conn0"
sw2[image]="nicolaka/netshoot"
sw2[0]="conn1"
sw2[1]="conn4"
sw3[image]="nicolaka/netshoot"
sw3[0]="conn5"
sw3[1]="conn6"
sw4[image]="nicolaka/netshoot"
sw4[0]="conn7"
sw5[image]="nicolaka/netshoot"
sw5[0]="conn2"
sw6[image]="nicolaka/netshoot"
sw6[0]="conn3"
